/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.*;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Main extends javax.swing.JFrame {

    private final String[] MonAn = {"Tên món ăn", "Giá", "Mô tả", "Số lượng"};
    private final DefaultTableModel tbMonAn = new DefaultTableModel(MonAn, 0);
    
    private final String[] KhachHang = {"Họ tên", "SĐT", "Email", "Địa chỉ"};
    private final DefaultTableModel tbKhachHang = new DefaultTableModel(KhachHang, 0);
    
    private final String[] DonHang = {"Mã đơn hàng", "Tên khách", "Số điện thoại", "Tổng tiền", "Mô tả"};
    private final DefaultTableModel tbDonHang = new DefaultTableModel(DonHang, 0);
    
//    private final String[] MonAnSL = {"Món ăn", "Số lượng"};
//    private final DefaultTableModel tbMonAnSL = new DefaultTableModel(MonAnSL, 0);
    
    DatabaseConnection cn = new DatabaseConnection();
    
    public Main() {
        initComponents();
        
        LoadData("SELECT TenMonAn, Gia, MoTa, SoLuongTon FROM MonAn", tbMonAn, jtbMonAn);
        LoadData("SELECT HoTen, SoDienThoai, Email, DiaChi FROM KhachHang", tbKhachHang, jtbKhachHang);
        LoadData("SELECT \n"
                + "    dh.MaDonHang, \n"
                + "    kh.HoTen AS TenKhachHang, \n"
                + "    kh.SoDienThoai AS SDT, \n"
                + "    dh.TongTien, \n"
                + "    ma.MoTa AS MoTaMonAn\n"
                + "FROM DonHang dh\n"
                + "JOIN KhachHang kh ON dh.MaKhachHang = kh.MaKhachHang\n"
                + "JOIN ChiTietDonHang ctdh ON dh.MaDonHang = ctdh.MaDonHang\n"
                + "JOIN MonAn ma ON ctdh.MaMonAn = ma.MaMonAn;", tbDonHang, jtbDSDonHang);
    }
    
    private void LoadData(String query, DefaultTableModel tableModel, javax.swing.JTable table) {
        List<Map<String, Object>> data = cn.executeQuery(query);
        tableModel.setRowCount(0);

        for (Map<String, Object> row : data) {
            Object[] rowData = row.values().toArray();
            tableModel.addRow(rowData);
        }
        table.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbMonAn = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jtxtTenMon = new javax.swing.JTextField();
        jtxtGia = new javax.swing.JTextField();
        jbtnThem = new javax.swing.JButton();
        jbtnXoa = new javax.swing.JButton();
        jbtnSua = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtMota = new javax.swing.JTextPane();
        jLabel16 = new javax.swing.JLabel();
        jtxtSoLuong = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jtxtSearch = new javax.swing.JTextField();
        jbtnTimKiem = new javax.swing.JButton();
        jbtnLamMoi = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtbKhachHang = new javax.swing.JTable();
        jtxtSearchKhach = new javax.swing.JTextField();
        jtxtTimKiemKhach = new javax.swing.JButton();
        jbtnLamMoiKhach = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jtxtHoTen = new javax.swing.JTextField();
        jtxtDiaChi = new javax.swing.JTextField();
        jtxtSDT = new javax.swing.JTextField();
        jtxtEmail = new javax.swing.JTextField();
        jbtnSuaKhach = new javax.swing.JButton();
        jbtnXoaKhach = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jtxtHoTenDonHang = new javax.swing.JTextField();
        jtxtSDTDonHang = new javax.swing.JTextField();
        jtxtTongTienDonHang = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        jtbMonAnSoLuong = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        jtxtMoTaDonHang = new javax.swing.JTextPane();
        jbtnThemDonHang = new javax.swing.JButton();
        jbtnXoaDonHang = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jtbDSDonHang = new javax.swing.JTable();
        jtxtTimKiemDonHang = new javax.swing.JTextField();
        jbtnTimKiemDonHang = new javax.swing.JButton();
        jbtnLamMoiDonHang = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 14)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jtbMonAn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbMonAn.setShowGrid(true);
        jtbMonAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbMonAnMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbMonAn);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jbtnThem.setText("Thêm ");
        jbtnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnThemActionPerformed(evt);
            }
        });

        jbtnXoa.setText("Xóa");
        jbtnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnXoaActionPerformed(evt);
            }
        });

        jbtnSua.setText("Sửa");
        jbtnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSuaActionPerformed(evt);
            }
        });

        jLabel1.setText("Tên món");

        jLabel2.setText("Giá");

        jLabel3.setText("Mô tả");

        jScrollPane2.setViewportView(jtxtMota);

        jLabel16.setText("Số lượng");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtTenMon, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtGia, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(jtxtSoLuong, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jbtnSua, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                .addGap(39, 39, 39)
                                .addComponent(jbtnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jbtnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jLabel2))
                                    .addComponent(jLabel3))
                                .addGap(111, 111, 111))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtTenMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addComponent(jbtnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(77, 77, 77))
        );

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        jbtnTimKiem.setText("Tìm kiếm");
        jbtnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTimKiemActionPerformed(evt);
            }
        });

        jbtnLamMoi.setText("Làm mới");
        jbtnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLamMoiActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Montserrat Black", 1, 22)); // NOI18N
        jLabel4.setText("DANH SÁCH CÁC MÓN ĂN");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtxtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addGap(40, 40, 40)
                .addComponent(jbtnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 509, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Danh sách món ăn", jPanel1);

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        jtbKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbKhachHangMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jtbKhachHang);

        jtxtTimKiemKhach.setText("Tìm kiếm");
        jtxtTimKiemKhach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTimKiemKhachActionPerformed(evt);
            }
        });

        jbtnLamMoiKhach.setText("Làm mới");
        jbtnLamMoiKhach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLamMoiKhachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jbtnLamMoiKhach, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addGap(375, 375, 375)
                .addComponent(jtxtSearchKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jtxtTimKiemKhach, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addGap(57, 57, 57))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtSearchKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtTimKiemKhach)
                    .addComponent(jbtnLamMoiKhach))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));

        jbtnSuaKhach.setText("Sửa");
        jbtnSuaKhach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSuaKhachActionPerformed(evt);
            }
        });

        jbtnXoaKhach.setText("Xóa");
        jbtnXoaKhach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnXoaKhachActionPerformed(evt);
            }
        });

        jLabel5.setText("Địa chỉ");

        jLabel6.setText("Email");

        jLabel7.setText("Họ tên");

        jLabel8.setText("Số điện thoại");

        jLabel9.setFont(new java.awt.Font("Montserrat Black", 0, 22)); // NOI18N
        jLabel9.setText("DANH SÁCH KHÁCH HÀNG");
        jLabel9.setToolTipText("");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtxtHoTen)
                        .addComponent(jtxtDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE))
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(42, 42, 42)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))
                        .addGap(149, 149, 149))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jtxtSDT)
                        .addGap(153, 153, 153)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnXoaKhach, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(jbtnSuaKhach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(83, 83, 83))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtHoTen)
                    .addComponent(jbtnSuaKhach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtDiaChi))
                        .addGap(1, 1, 1))
                    .addComponent(jbtnXoaKhach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Danh sách khách hàng", jPanel2);

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setFont(new java.awt.Font("Montserrat Black", 0, 22)); // NOI18N
        jLabel10.setText("DANH SÁCH ĐƠN HÀNG");

        jtxtHoTenDonHang.setPreferredSize(new java.awt.Dimension(150, 22));

        jtxtSDTDonHang.setPreferredSize(new java.awt.Dimension(150, 22));

        jtxtTongTienDonHang.setPreferredSize(new java.awt.Dimension(100, 22));

        jtbMonAnSoLuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Món Ăn", "Số lượng"
            }
        ));
        jScrollPane7.setViewportView(jtbMonAnSoLuong);

        jScrollPane8.setViewportView(jtxtMoTaDonHang);

        jbtnThemDonHang.setText("Thêm");
        jbtnThemDonHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnThemDonHangActionPerformed(evt);
            }
        });

        jbtnXoaDonHang.setText("Xóa");
        jbtnXoaDonHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnXoaDonHangActionPerformed(evt);
            }
        });

        jLabel11.setText("Họ tên ");

        jLabel13.setText("Số điện thoại");

        jLabel14.setText("Tổng tiền");

        jLabel15.setText("Mô tả");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jbtnThemDonHang)
                        .addGap(98, 98, 98)
                        .addComponent(jbtnXoaDonHang))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtSDTDonHang, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(jtxtHoTenDonHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtTongTienDonHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(75, 75, 75)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jLabel15))
                .addGap(17, 17, 17))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(351, 351, 351)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jtxtHoTenDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtxtTongTienDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtSDTDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbtnThemDonHang)
                                    .addComponent(jbtnXoaDonHang)))
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(254, 254, 254))
        );

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));
        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtbDSDonHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jtbDSDonHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbDSDonHangMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jtbDSDonHang);

        jbtnTimKiemDonHang.setText("tìm kiếm");
        jbtnTimKiemDonHang.setActionCommand("Tìm kiếm");
        jbtnTimKiemDonHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTimKiemDonHangActionPerformed(evt);
            }
        });

        jbtnLamMoiDonHang.setText("Làm mới");
        jbtnLamMoiDonHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLamMoiDonHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jtxtTimKiemDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnTimKiemDonHang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnLamMoiDonHang)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtTimKiemDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnTimKiemDonHang)
                    .addComponent(jbtnLamMoiDonHang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 262, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Danh sách đơn hàng", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnThemDonHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnThemDonHangActionPerformed
        ThemDON orderForm = new ThemDON();
    orderForm.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jbtnThemDonHangActionPerformed

    private void jbtnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLamMoiActionPerformed
        LoadData("SELECT TenMonAn, Gia, MoTa, SoLuongTon FROM MonAn", tbMonAn, jtbMonAn);
    }//GEN-LAST:event_jbtnLamMoiActionPerformed

    private void jtbMonAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbMonAnMouseClicked

        int selectedRow = jtbMonAn.getSelectedRow();
        if (selectedRow != -1) {
            jtxtTenMon.setText(jtbMonAn.getValueAt(selectedRow, 0).toString());
            jtxtGia.setText(jtbMonAn.getValueAt(selectedRow, 1).toString());
            jtxtMota.setText(jtbMonAn.getValueAt(selectedRow, 2).toString());
            jtxtSoLuong.setText(jtbMonAn.getValueAt(selectedRow, 3).toString());
        }
    }//GEN-LAST:event_jtbMonAnMouseClicked

    private void jtbKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbKhachHangMouseClicked
        int selectedRow = jtbKhachHang.getSelectedRow();
        if (selectedRow != -1) {
            jtxtHoTen.setText(jtbKhachHang.getValueAt(selectedRow, 0).toString());
            jtxtSDT.setText(jtbKhachHang.getValueAt(selectedRow, 1).toString());
            jtxtEmail.setText(jtbKhachHang.getValueAt(selectedRow, 2).toString());
            jtxtDiaChi.setText(jtbKhachHang.getValueAt(selectedRow, 3).toString());
        }
    }//GEN-LAST:event_jtbKhachHangMouseClicked

    private void jbtnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSuaActionPerformed
        int selectedRow = jtbMonAn.getSelectedRow();
        
        String tenMon = jtxtTenMon.getText();
        String gia = jtxtGia.getText();
        String moTa = jtxtMota.getText();
        String soLuong = jtxtSoLuong.getText();
        
        String tenMonCu = jtbMonAn.getValueAt(selectedRow, 0).toString();
        
        if(tenMon.isEmpty() || gia.isEmpty() || moTa.isEmpty() || soLuong.isEmpty()){
            JOptionPane.showMessageDialog(this, "Không được để trống!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        return;
        }
        
        try {
            String query = "UPDATE MonAn SET TenMonAn = ?, Gia = ?, MoTa = ?, SoLuongTon = ? WHERE TenMonAn = ?";
        int rowsAffected = cn.executeUpdate(query, tenMon, gia, moTa, soLuong, tenMonCu);

        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
            LoadData("SELECT TenMonAn, Gia, MoTa, SoLuongTon FROM MonAn", tbMonAn, jtbMonAn);
        } else {
            JOptionPane.showMessageDialog(this, "Cập nhật thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jbtnSuaActionPerformed

    private void jbtnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnXoaActionPerformed
        int selectedRow = jtbMonAn.getSelectedRow();
        
        String tenMon = jtbMonAn.getValueAt(selectedRow, 0).toString();
        
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa món: " + tenMon + "?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                String query = "DELETE FROM MonAn WHERE TenMonAn = ?";
                int rowsAffected = cn.executeUpdate(query, tenMon);

                if (rowsAffected > 0) {
                    //JOptionPane.showMessageDialog(this, "Đã xóa");
                    LoadData("SELECT TenMonAn, Gia, MoTa, SoLuongTon FROM MonAn", tbMonAn, jtbMonAn);
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jbtnXoaActionPerformed

    private void jbtnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnThemActionPerformed
        String tenMon = jtxtTenMon.getText();
        String gia = jtxtGia.getText();
        String moTa = jtxtMota.getText();
        String soLuong = jtxtSoLuong.getText();
        
        if (tenMon.isEmpty() || gia.isEmpty() || moTa.isEmpty() || soLuong.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa điền hết", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            String query = "INSERT INTO MonAn (TenMonAn, Gia, MoTa, SoLuongTon) VALUES (?, ?, ?, ?)";
            int rowsAffected = cn.executeUpdate(query, tenMon, gia, moTa, soLuong);

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Đã theem");
                LoadData("SELECT TenMonAn, Gia, MoTa, SoLuongTon FROM MonAn", tbMonAn, jtbMonAn);
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jbtnThemActionPerformed

    private void jbtnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTimKiemActionPerformed
        String timKiem = jtxtSearch.getText().trim();

        String query = "SELECT TenMonAn, Gia, MoTa, SoLuongTon FROM MonAn WHERE TenMonAn LIKE ?";

        List<Map<String, Object>> data = DatabaseConnection.executeQuery(query, "%" + timKiem + "%");

        tbMonAn.setRowCount(0);

        for (Map<String, Object> row : data) {
            Object[] rowData = row.values().toArray();
            tbMonAn.addRow(rowData);
        }

        jtbMonAn.setModel(tbMonAn);
    }//GEN-LAST:event_jbtnTimKiemActionPerformed

    private void jbtnSuaKhachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSuaKhachActionPerformed
        int selectedRow = jtbKhachHang.getSelectedRow();
        
        String HoTen = jtxtHoTen.getText();
        String SDT = jtxtSDT.getText();
        String Email = jtxtEmail.getText();
        String diaChi = jtxtDiaChi.getText();
        
        String KhachCu = jtbKhachHang.getValueAt(selectedRow, 0).toString();
        
        if(HoTen.isEmpty() || SDT.isEmpty() || Email.isEmpty() || diaChi.isEmpty()){
            JOptionPane.showMessageDialog(this, "Không được để trống!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        return;
        }
        
        try {
            String query = "UPDATE KhachHang SET HoTen = ?, SoDienThoai = ?, Email = ?, DiaChi = ? WHERE HoTen = ?";
        int rowsAffected = cn.executeUpdate(query, HoTen, SDT, Email, diaChi, KhachCu);

        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
            LoadData("SELECT HoTen, SoDienThoai, Email, DiaChi FROM KhachHang", tbKhachHang, jtbKhachHang);
        } else {
            JOptionPane.showMessageDialog(this, "Cập nhật thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jbtnSuaKhachActionPerformed

    private void jbtnLamMoiKhachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLamMoiKhachActionPerformed
        LoadData("SELECT HoTen, SoDienThoai, Email, DiaChi FROM KhachHang", tbKhachHang, jtbKhachHang);
    }//GEN-LAST:event_jbtnLamMoiKhachActionPerformed

    private void jbtnXoaKhachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnXoaKhachActionPerformed
        int selectedRow = jtbKhachHang.getSelectedRow();
        
        String hoTen = jtbKhachHang.getValueAt(selectedRow, 0).toString();
        
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa món: " + hoTen + "?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                String query = "DELETE FROM KhachHang WHERE HoTen = ?";
                int rowsAffected = cn.executeUpdate(query, hoTen);

                if (rowsAffected > 0) {
                    //JOptionPane.showMessageDialog(this, "Đã xóa");
                    LoadData("SELECT HoTen, SoDienThoai, Email, DiaChi FROM KhachHang", tbKhachHang, jtbKhachHang);
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jbtnXoaKhachActionPerformed

    private void jtxtTimKiemKhachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTimKiemKhachActionPerformed
        String timKiemKhach = jtxtSearchKhach.getText().trim();

        String query = "SELECT HoTen, SoDienThoai, Email, DiaChi FROM KhachHang WHERE HoTen LIKE ?";

        List<Map<String, Object>> data = DatabaseConnection.executeQuery(query, "%" + timKiemKhach + "%");

        tbKhachHang.setRowCount(0);

        for (Map<String, Object> row : data) {
            Object[] rowData = row.values().toArray();
            tbKhachHang.addRow(rowData);
        }

        jtbKhachHang.setModel(tbKhachHang);
    }//GEN-LAST:event_jtxtTimKiemKhachActionPerformed

    private void jtbDSDonHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbDSDonHangMouseClicked
        int selectedRow = jtbDSDonHang.getSelectedRow();
        if (selectedRow != -1) {
            jtxtHoTenDonHang.setText(jtbDSDonHang.getValueAt(selectedRow, 1).toString());
            jtxtSDTDonHang.setText(jtbDSDonHang.getValueAt(selectedRow, 2).toString());
            jtxtTongTienDonHang.setText(jtbDSDonHang.getValueAt(selectedRow, 3).toString());
            jtxtMoTaDonHang.setText(jtbDSDonHang.getValueAt(selectedRow, 4).toString());

            // Lấy mã đơn hàng
            String maDonHang = jtbDSDonHang.getValueAt(selectedRow, 0).toString();

            // Truy vấn danh sách món ăn và số lượng trong đơn hàng
            String query = "SELECT ma.TenMonAn, ctdh.SoLuong "
                    + "FROM ChiTietDonHang ctdh "
                    + "JOIN MonAn ma ON ctdh.MaMonAn = ma.MaMonAn "
                    + "WHERE ctdh.MaDonHang = ?";

            List<Map<String, Object>> danhSachMonAn = DatabaseConnection.executeQuery(query, maDonHang);

            // Xóa dữ liệu cũ trong bảng jtbMonAnSL
            DefaultTableModel model = (DefaultTableModel) jtbMonAnSoLuong.getModel();
            model.setRowCount(0);

            // Đổ dữ liệu mới vào bảng jtbMonAnSL
            for (Map<String, Object> row : danhSachMonAn) {
                model.addRow(new Object[]{
                    row.get("TenMonAn"),
                    row.get("SoLuong")
                });
            }
        }
    }//GEN-LAST:event_jtbDSDonHangMouseClicked

    private void jbtnXoaDonHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnXoaDonHangActionPerformed
        int selectedRow = jtbDSDonHang.getSelectedRow();
        
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa đơn hàng này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        
        String maDonHang = jtbDSDonHang.getValueAt(selectedRow, 0).toString();
        
        try (Connection conn = DatabaseConnection.getConnection()) {
        conn.setAutoCommit(false);
        
        // Xóa dữ liệu trong ChiTietDonHang trước
        String deleteChiTietQuery = "DELETE FROM ChiTietDonHang WHERE MaDonHang = ?";
        int rowsDeletedChiTiet = DatabaseConnection.executeUpdate(deleteChiTietQuery, maDonHang);

        // Xóa đơn hàng trong DonHang
        String deleteDonHangQuery = "DELETE FROM DonHang WHERE MaDonHang = ?";
        int rowsDeletedDonHang = DatabaseConnection.executeUpdate(deleteDonHangQuery, maDonHang);
        // xoá khách 
        String deleteKhachHangQuery = "DELETE FROM KhachHang WHERE MaKhachHang = ?";
        int rowsDeletedKhachHang = DatabaseConnection.executeUpdate(deleteKhachHangQuery, maDonHang);
        
        if (rowsDeletedChiTiet >= 0 && rowsDeletedDonHang >= 0) {
            conn.commit();
            JOptionPane.showMessageDialog(this, "Xóa đơn hàng thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            conn.rollback();
            JOptionPane.showMessageDialog(this, "Lỗi khi xóa đơn hàng!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }

        LoadData("SELECT \n"
                + "    dh.MaDonHang, \n"
                + "    kh.HoTen AS TenKhachHang, \n"
                + "    kh.SoDienThoai AS SDT, \n"
                + "    dh.TongTien, \n"
                + "    ma.MoTa AS MoTaMonAn\n"
                + "FROM DonHang dh\n"
                + "JOIN KhachHang kh ON dh.MaKhachHang = kh.MaKhachHang\n"
                + "JOIN ChiTietDonHang ctdh ON dh.MaDonHang = ctdh.MaDonHang\n"
                + "JOIN MonAn ma ON ctdh.MaMonAn = ma.MaMonAn;", tbDonHang, jtbDSDonHang);
        
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi khi xóa đơn hàng: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jbtnXoaDonHangActionPerformed

    private void jbtnLamMoiDonHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLamMoiDonHangActionPerformed
        LoadData("SELECT \n"
                + "    dh.MaDonHang, \n"
                + "    kh.HoTen AS TenKhachHang, \n"
                + "    kh.SoDienThoai AS SDT, \n"
                + "    dh.TongTien, \n"
                + "    ma.MoTa AS MoTaMonAn\n"
                + "FROM DonHang dh\n"
                + "JOIN KhachHang kh ON dh.MaKhachHang = kh.MaKhachHang\n"
                + "JOIN ChiTietDonHang ctdh ON dh.MaDonHang = ctdh.MaDonHang\n"
                + "JOIN MonAn ma ON ctdh.MaMonAn = ma.MaMonAn;", tbDonHang, jtbDSDonHang);
    }//GEN-LAST:event_jbtnLamMoiDonHangActionPerformed

    private void jbtnTimKiemDonHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTimKiemDonHangActionPerformed
        String timKiemKhach = jtxtTimKiemDonHang.getText().trim();

        String query = "SELECT " +
               "    dh.MaDonHang, " +
               "    kh.HoTen AS TenKhachHang, " +
               "    kh.SoDienThoai AS SDT, " +
               "    dh.TongTien, " +
               "    ma.MoTa AS MoTaMonAn " +
               "FROM DonHang dh " +
               "JOIN KhachHang kh ON dh.MaKhachHang = kh.MaKhachHang " +
               "JOIN ChiTietDonHang ctdh ON dh.MaDonHang = ctdh.MaDonHang " +
               "JOIN MonAn ma ON ctdh.MaMonAn = ma.MaMonAn " +
               "WHERE kh.SoDienThoai LIKE ?";
        
        List<Map<String, Object>> data = DatabaseConnection.executeQuery(query, "%" + timKiemKhach + "%");

        tbDonHang.setRowCount(0);

        for (Map<String, Object> row : data) {
            Object[] rowData = row.values().toArray();
            tbDonHang.addRow(rowData);
        }

        jtbDSDonHang.setModel(tbDonHang);
    }//GEN-LAST:event_jbtnTimKiemDonHangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JButton jbtnLamMoi;
    private javax.swing.JButton jbtnLamMoiDonHang;
    private javax.swing.JButton jbtnLamMoiKhach;
    private javax.swing.JButton jbtnSua;
    private javax.swing.JButton jbtnSuaKhach;
    private javax.swing.JButton jbtnThem;
    private javax.swing.JButton jbtnThemDonHang;
    private javax.swing.JButton jbtnTimKiem;
    private javax.swing.JButton jbtnTimKiemDonHang;
    private javax.swing.JButton jbtnXoa;
    private javax.swing.JButton jbtnXoaDonHang;
    private javax.swing.JButton jbtnXoaKhach;
    private javax.swing.JTable jtbDSDonHang;
    private javax.swing.JTable jtbKhachHang;
    private javax.swing.JTable jtbMonAn;
    private javax.swing.JTable jtbMonAnSoLuong;
    private javax.swing.JTextField jtxtDiaChi;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtGia;
    private javax.swing.JTextField jtxtHoTen;
    private javax.swing.JTextField jtxtHoTenDonHang;
    private javax.swing.JTextPane jtxtMoTaDonHang;
    private javax.swing.JTextPane jtxtMota;
    private javax.swing.JTextField jtxtSDT;
    private javax.swing.JTextField jtxtSDTDonHang;
    private javax.swing.JTextField jtxtSearch;
    private javax.swing.JTextField jtxtSearchKhach;
    private javax.swing.JTextField jtxtSoLuong;
    private javax.swing.JTextField jtxtTenMon;
    private javax.swing.JTextField jtxtTimKiemDonHang;
    private javax.swing.JButton jtxtTimKiemKhach;
    private javax.swing.JTextField jtxtTongTienDonHang;
    // End of variables declaration//GEN-END:variables
}
